[project]
name = "flet-tube"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "flet[all]==0.25.1",
    "pytubefix>=8.13.1",
]
